FROM lct-analytics-vlm-llm:0.5.0

COPY --chown=10001:10001 construction_analytics/vlm.py /opt/analytics/construction_analytics/vlm.py
COPY --chown=10001:10001 construction_analytics/pipeline.py /opt/analytics/construction_analytics/pipeline.py
